### ISSUE TITLE
Issue with robust_correlation for one particular variable containing a value of "0"

### ISSUE THREAD

**Issue by MarcusHarrington** [CPernet/Robust-Correlations#11]
When I run the robust_correlation function to investigate the relationship between two particular variables, MATLAB crashes before calculating Pearson's skipped correlation. We have one participant in there who scored "0" on one of the measures. Curiously, when I remove that participant, or change that participant's score to 0.0001, the robust_correlation function works perfectly fine. Is this a known bug? If so, do you know of a workaround? I have attached the data in case you would like to take a look for yourself. x = A1:A57, y = B1:B57.

Thanks!

[RobustCorrelationData.xlsx](https://github.com/CPernet/Robust-Correlations/files/7906255/RobustCorrelationData.xlsx)

**Comment by CPernet** [comment]
looks like an issue creating the figure??? is that right -- I updated the function to stop if no convergence and I could run the code on your variables

**Comment by GRousselet** [comment]
I've just tried robust_correlation() on the data: all the figures are generated without any error message.

**Comment by MarcusHarrington** [comment]
I'm happy to confirm that this issue is now fixed. Thank you!
