### ISSUE TITLE
Some questions about Pearson.m in  Verb.1

### ISSUE THREAD

**Issue by maohy915** [CPernet/Robust-Correlations#6]
Hello Pernet, 
I'v read your paper _Robust correlation analyses: false positive and powervalidation using a new open source Matlab toolbox_ and now I'm trying to use your toolbox code verb.1, but I got few questions about  the code in Pearson.m. Is var **nboot** means  the ressamples in bootstrap procedure (I dont't get the 10,000 resamples mentioned in the paper, is the procedure run in the coed? )? Why **nboot** is set to 599 when nargout>3? And what the vars **low** and **high** are used for?
Looking for your answers, tk u verrrry much!

**Comment by CPernet** [comment]
in the paper 10.000 is the number of Monte Carlo simulations, at each simulation run eg Pearson with 599 bootstraps (nboot) the default
