### ISSUE TITLE
Error in Pearson function

### ISSUE THREAD

**Issue by AgustinSolano** [CPernet/Robust-Correlations#7]
Hi. I am having this error message. I see that the current Pearson function does not return the 'hboot' var, needed in line 82 of 'robust_correlation.m'

_Error using Pearson
Too many output arguments.

Error in robust_correlation (line 82)
[r,t,pval,hboot,CI] = Pearson(X,Y);_

**Comment by AgustinSolano** [comment]
The 'hboot' var is also missing in the Spearman function and needed inside 'bendcorr.m'

**Comment by CPernet** [comment]
what version do you use v2 is stable - master is work in progress

**Comment by AgustinSolano** [comment]
I was using the master branch, sorry about that. I checked v2 and it is working properly. Thanks!
